# Generated by Django 5.2 on 2025-04-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('price', models.IntegerField()),
                ('available', models.BooleanField(null=True)),
            ],
        ),
    ]
