# Generated by Django 5.2 on 2025-04-10 20:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='address',
        ),
        migrations.AddField(
            model_name='hotel',
            name='available_until',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
