# Generated by Django 5.2 on 2025-04-10 20:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapi', '0002_remove_hotel_address_hotel_available_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_number', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('hotel_name', models.CharField(max_length=100)),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('guests', models.ManyToManyField(to='hotelapi.guest')),
            ],
        ),
    ]
